version: '3'
 
services:
  whip:
    environment:
      - HOST_NAME="https://whip.automateyournetwork.ca"
    container_name: whip  
    image: johncapobianco/whip:whip
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile
    ports:
      - "8002:8002"
    depends_on:
      - db
    volumes:
      - /etc/letsencrypt/archive/whip.automateyournetwork.ca/:/etc/letsencrypt/live/whip.automateyournetwork.ca/

  db:
    image: 'postgres'
    environment:
      - POSTGRES_USER=whip
      - POSTGRES_PASSWORD=whip
      - POSTGRES_DB=whip
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5434:5432"

volumes:
  pgadmin:
    driver: local