version: '3'
 
services:
  whip:
    image: johncapobianco/whip:whip
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile
    ports:
      - "80:8000"
    depends_on:
      - db
    # volumes:
    #   - /etc/letsencrypt/archive/whip.automateyournetwork.ca/:/etc/letsencrypt/live/whip.automateyournetwork.ca/

  db:
    image: 'postgres'
    environment:
      - POSTGRES_USER=whip
      - POSTGRES_PASSWORD=whip
      - POSTGRES_DB=whip
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgadmin:
    driver: local